# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20161103134922) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"
  enable_extension "postgis"

  create_table "data", force: :cascade do |t|
    t.string   "description"
    t.decimal  "value"
    t.integer  "year"
    t.string   "imageable_type"
    t.integer  "imageable_id"
    t.datetime "created_at",     null: false
    t.datetime "updated_at",     null: false
    t.index ["imageable_type", "imageable_id"], name: "index_data_on_imageable_type_and_imageable_id", using: :btree
  end

  create_table "districts", force: :cascade do |t|
    t.string   "name"
    t.datetime "created_at",                                          null: false
    t.datetime "updated_at",                                          null: false
    t.geometry "way",        limit: {:srid=>4326, :type=>"geometry"}
  end

  create_table "planet_osm_line", id: false, force: :cascade do |t|
    t.bigint   "osm_id"
    t.text     "access"
    t.text     "addr:housename"
    t.text     "addr:housenumber"
    t.text     "addr:interpolation"
    t.text     "admin_level"
    t.text     "aerialway"
    t.text     "aeroway"
    t.text     "amenity"
    t.text     "area"
    t.text     "barrier"
    t.text     "bicycle"
    t.text     "brand"
    t.text     "bridge"
    t.text     "boundary"
    t.text     "building"
    t.text     "construction"
    t.text     "covered"
    t.text     "culvert"
    t.text     "cutting"
    t.text     "denomination"
    t.text     "disused"
    t.text     "embankment"
    t.text     "foot"
    t.text     "generator:source"
    t.text     "harbour"
    t.text     "highway"
    t.text     "historic"
    t.text     "horse"
    t.text     "intermittent"
    t.text     "junction"
    t.text     "landuse"
    t.text     "layer"
    t.text     "leisure"
    t.text     "lock"
    t.text     "man_made"
    t.text     "military"
    t.text     "motorcar"
    t.text     "name"
    t.text     "natural"
    t.text     "office"
    t.text     "oneway"
    t.text     "operator"
    t.text     "place"
    t.text     "population"
    t.text     "power"
    t.text     "power_source"
    t.text     "public_transport"
    t.text     "railway"
    t.text     "ref"
    t.text     "religion"
    t.text     "route"
    t.text     "service"
    t.text     "shop"
    t.text     "sport"
    t.text     "surface"
    t.text     "toll"
    t.text     "tourism"
    t.text     "tower:type"
    t.text     "tracktype"
    t.text     "tunnel"
    t.text     "water"
    t.text     "waterway"
    t.text     "wetland"
    t.text     "width"
    t.text     "wood"
    t.integer  "z_order"
    t.float    "way_area"
    t.geometry "way",                limit: {:srid=>900913, :type=>"line_string"}
    t.index ["way"], name: "planet_osm_line_index", using: :gist
  end

  create_table "planet_osm_point", id: false, force: :cascade do |t|
    t.bigint   "osm_id"
    t.text     "access"
    t.text     "addr:housename"
    t.text     "addr:housenumber"
    t.text     "addr:interpolation"
    t.text     "admin_level"
    t.text     "aerialway"
    t.text     "aeroway"
    t.text     "amenity"
    t.text     "area"
    t.text     "barrier"
    t.text     "bicycle"
    t.text     "brand"
    t.text     "bridge"
    t.text     "boundary"
    t.text     "building"
    t.text     "capital"
    t.text     "construction"
    t.text     "covered"
    t.text     "culvert"
    t.text     "cutting"
    t.text     "denomination"
    t.text     "disused"
    t.text     "ele"
    t.text     "embankment"
    t.text     "foot"
    t.text     "generator:source"
    t.text     "harbour"
    t.text     "highway"
    t.text     "historic"
    t.text     "horse"
    t.text     "intermittent"
    t.text     "junction"
    t.text     "landuse"
    t.text     "layer"
    t.text     "leisure"
    t.text     "lock"
    t.text     "man_made"
    t.text     "military"
    t.text     "motorcar"
    t.text     "name"
    t.text     "natural"
    t.text     "office"
    t.text     "oneway"
    t.text     "operator"
    t.text     "place"
    t.text     "poi"
    t.text     "population"
    t.text     "power"
    t.text     "power_source"
    t.text     "public_transport"
    t.text     "railway"
    t.text     "ref"
    t.text     "religion"
    t.text     "route"
    t.text     "service"
    t.text     "shop"
    t.text     "sport"
    t.text     "surface"
    t.text     "toll"
    t.text     "tourism"
    t.text     "tower:type"
    t.text     "tunnel"
    t.text     "water"
    t.text     "waterway"
    t.text     "wetland"
    t.text     "width"
    t.text     "wood"
    t.integer  "z_order"
    t.geometry "way",                limit: {:srid=>900913, :type=>"point"}
    t.index ["way"], name: "planet_osm_point_index", using: :gist
  end

  create_table "planet_osm_polygon", id: false, force: :cascade do |t|
    t.bigint   "osm_id"
    t.text     "access"
    t.text     "addr:housename"
    t.text     "addr:housenumber"
    t.text     "addr:interpolation"
    t.text     "admin_level"
    t.text     "aerialway"
    t.text     "aeroway"
    t.text     "amenity"
    t.text     "area"
    t.text     "barrier"
    t.text     "bicycle"
    t.text     "brand"
    t.text     "bridge"
    t.text     "boundary"
    t.text     "building"
    t.text     "construction"
    t.text     "covered"
    t.text     "culvert"
    t.text     "cutting"
    t.text     "denomination"
    t.text     "disused"
    t.text     "embankment"
    t.text     "foot"
    t.text     "generator:source"
    t.text     "harbour"
    t.text     "highway"
    t.text     "historic"
    t.text     "horse"
    t.text     "intermittent"
    t.text     "junction"
    t.text     "landuse"
    t.text     "layer"
    t.text     "leisure"
    t.text     "lock"
    t.text     "man_made"
    t.text     "military"
    t.text     "motorcar"
    t.text     "name"
    t.text     "natural"
    t.text     "office"
    t.text     "oneway"
    t.text     "operator"
    t.text     "place"
    t.text     "population"
    t.text     "power"
    t.text     "power_source"
    t.text     "public_transport"
    t.text     "railway"
    t.text     "ref"
    t.text     "religion"
    t.text     "route"
    t.text     "service"
    t.text     "shop"
    t.text     "sport"
    t.text     "surface"
    t.text     "toll"
    t.text     "tourism"
    t.text     "tower:type"
    t.text     "tracktype"
    t.text     "tunnel"
    t.text     "water"
    t.text     "waterway"
    t.text     "wetland"
    t.text     "width"
    t.text     "wood"
    t.integer  "z_order"
    t.float    "way_area"
    t.geometry "way",                limit: {:srid=>900913, :type=>"geometry"}
    t.index ["way"], name: "planet_osm_polygon_index", using: :gist
  end

  create_table "planet_osm_roads", id: false, force: :cascade do |t|
    t.bigint   "osm_id"
    t.text     "access"
    t.text     "addr:housename"
    t.text     "addr:housenumber"
    t.text     "addr:interpolation"
    t.text     "admin_level"
    t.text     "aerialway"
    t.text     "aeroway"
    t.text     "amenity"
    t.text     "area"
    t.text     "barrier"
    t.text     "bicycle"
    t.text     "brand"
    t.text     "bridge"
    t.text     "boundary"
    t.text     "building"
    t.text     "construction"
    t.text     "covered"
    t.text     "culvert"
    t.text     "cutting"
    t.text     "denomination"
    t.text     "disused"
    t.text     "embankment"
    t.text     "foot"
    t.text     "generator:source"
    t.text     "harbour"
    t.text     "highway"
    t.text     "historic"
    t.text     "horse"
    t.text     "intermittent"
    t.text     "junction"
    t.text     "landuse"
    t.text     "layer"
    t.text     "leisure"
    t.text     "lock"
    t.text     "man_made"
    t.text     "military"
    t.text     "motorcar"
    t.text     "name"
    t.text     "natural"
    t.text     "office"
    t.text     "oneway"
    t.text     "operator"
    t.text     "place"
    t.text     "population"
    t.text     "power"
    t.text     "power_source"
    t.text     "public_transport"
    t.text     "railway"
    t.text     "ref"
    t.text     "religion"
    t.text     "route"
    t.text     "service"
    t.text     "shop"
    t.text     "sport"
    t.text     "surface"
    t.text     "toll"
    t.text     "tourism"
    t.text     "tower:type"
    t.text     "tracktype"
    t.text     "tunnel"
    t.text     "water"
    t.text     "waterway"
    t.text     "wetland"
    t.text     "width"
    t.text     "wood"
    t.integer  "z_order"
    t.float    "way_area"
    t.geometry "way",                limit: {:srid=>900913, :type=>"line_string"}
    t.index ["way"], name: "planet_osm_roads_index", using: :gist
  end

  create_table "regions", force: :cascade do |t|
    t.string   "name"
    t.datetime "created_at",                                          null: false
    t.datetime "updated_at",                                          null: false
    t.geometry "way",        limit: {:srid=>4326, :type=>"geometry"}
  end

end
